# Generated by Django 4.2 on 2024-06-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mousignator',
            name='meta',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mou',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
