# Generated by Django 4.2 on 2025-06-17 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousignator',
            name='role_type',
            field=models.CharField(choices=[('highschool_admin', 'School Administrator'), ('district_admin', 'District Administrator'), ('college_admin', 'College Administrator')], default='highschool_admin', max_length=100, verbose_name='Role Type'),
        ),
    ]
