# Generated by Django 5.2.14 on 2026-05-15 14:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0002_alter_mousignator_role_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mou',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='managed_mous', to=settings.AUTH_USER_MODEL, verbose_name='MOU Manager'),
        ),
        migrations.AlterField(
            model_name='mousignature',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Not Ready To Sign'), ('pending', 'Pending Signature'), ('changes_requested', 'Changes Requested'), ('signed', 'Signed')], max_length=20, null=True, verbose_name='Status'),
        ),
    ]
