# Generated by Django 4.2 on 2024-06-03 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0002_mousignator_meta_alter_mou_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='mousignature',
            name='signator_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='mou.mousignator', verbose_name='Signator Templates'),
        ),
        migrations.AlterField(
            model_name='mou',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('ready', 'Ready')], default='draft', max_length=10, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='mousignature',
            name='status',
            field=models.CharField(blank=True, choices=[('', 'Not Ready To Sign'), ('pending', 'Pending Signature'), ('signed', 'Signed')], max_length=10, null=True, verbose_name='Status'),
        ),
    ]
