# Generated by Django 5.2 for college signator user+title (SCCC 6-step college-first chain).

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0003_mou_manager_and_change_request'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='mousignator',
            name='college_user',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='mou_college_signator_roles',
                to=settings.AUTH_USER_MODEL,
                verbose_name='College Signer',
            ),
        ),
        migrations.AddField(
            model_name='mousignator',
            name='title',
            field=models.CharField(
                blank=True,
                default='',
                help_text='Shown on the signature block. Used for college administrators; school/district rows still resolve the position name.',
                max_length=200,
                verbose_name='Signer Title',
            ),
        ),
    ]
