# Generated by Django 4.2 on 2024-06-03 14:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cis', '0002_initial'),
        ('mou', '0003_mousignature_signator_template_alter_mou_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='mousignature',
            unique_together={('highschool', 'signator', 'signator_template')},
        ),
    ]
