# Generated by Django 4.2 on 2024-06-10 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0004_alter_mousignature_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mousignature',
            name='signator_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mou.mousignator', verbose_name='Signator Templates'),
        ),
    ]
