# Generated by Django 4.2 on 2024-06-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0005_alter_mousignature_signator_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='mou',
            name='cron',
            field=models.CharField(default='123', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mou',
            name='send_on_after',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mou',
            name='send_until',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
