# Generated by Django 4.2 on 2024-07-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mou', '0006_mou_cron_mou_send_on_after_mou_send_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mou',
            name='status',
            field=models.CharField(blank=True, choices=[('draft', 'Draft'), ('ready', 'Ready to Send')], default='draft', max_length=10, null=True, verbose_name='Status'),
        ),
    ]
